apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops
  namespace: devopsapp
  labels:
    app: devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - name: devops
        image: mhmtogt/devops:v1
        ports:
        - containerPort: 4000
